export * from './types.js'
export * from './errors.js'
export { logger } from './logger/index.js'
export type { LogLevel, LogEntry } from './logger/index.js'
export { formatUserError, installGlobalErrorHandlers } from './errors/handler.js'
export type { Provider } from './provider/index.js'
export { BaseProvider, ProviderRegistry } from './provider/index.js'
export { ModelRegistry } from './registry/index.js'
export { ModelRouter } from './router/index.js'
export type { RouterRequest } from './router/index.js'
export { ContextManager } from './context/index.js'
export type { ContextConfig } from './context/index.js'
export { SessionManager } from './session/index.js'
export type { Session, SessionMetadata, SessionSummary } from './session/index.js'
export { AgentLoop } from './agent/index.js'
export type { AgentLoopOptions } from './agent/index.js'
export { ConfigManager } from './config/index.js'
export type { ArixConfig, NamedProfile } from './config/index.js'
export { SkillManager } from './skills/index.js'
export type { SkillDefinition } from './skills/index.js'
export { PluginRegistry } from './plugins/index.js'
export type { ArixPlugin, PluginToolRegistry } from './plugins/index.js'
export { MarketplaceClient } from './marketplace/index.js'
export type { MarketplaceEntry } from './marketplace/index.js'
export { CoordinatorAgent, TeamMemory } from './coordinator/index.js'
export type { CoordinatorOptions, SubTask, TaskType, TeamMemoryEntry } from './coordinator/index.js'
export { FeatureFlagManager } from './features/index.js'
export type { FeatureFlags } from './features/index.js'
export { ModelCatalogue } from './registry/models.js'
export type { TaskTier, RouteOptions, CatalogueEntry } from './registry/models.js'
export { CostTracker } from './cost/index.js'
export type { TurnCost, SessionCost, CostSummary } from './cost/index.js'
export { ContextCompactor, estimateTokens } from './compact/index.js'
export type { CompactOptions, CompactResult } from './compact/index.js'
export { ProjectMemory } from './memory/project.js'
export type { MemoryFact, ProjectMemoryData } from './memory/project.js'
export { ParallelAgentPool, mergeResults } from './parallel/index.js'
export type { WorkerTask, WorkerResult, ParallelPoolOptions } from './parallel/index.js'
export { PluginLoader } from './plugins/index.js'
export type { PluginManifest, DiskPluginModule, LoadedPlugin } from './plugins/index.js'
export { McpClient, McpRegistry, McpToolAdapter, StdioTransport, HttpTransport } from './mcp/index.js'
export type { McpServerConfig, McpTool, McpTransportType, McpCallToolResult, McpCatalogEntry } from './mcp/index.js'
export { MCP_PROTOCOL_VERSION, MCP_CATALOG, findMcpEntry, materialiseMcpEntry } from './mcp/index.js'
export { ToolResultCache } from './agent/cache.js'
export type { ToolCacheOptions } from './agent/cache.js'
export { planTurn, reflectTurn } from './agent/plan-reflect.js'
export type { PlanReflectOptions, PlanReflectProvider } from './agent/plan-reflect.js'
export { HardBudget, BudgetExceededError } from './agent/budget.js'
export type { HardBudgetOptions } from './agent/budget.js'
export { UndoStack } from './agent/undo.js'
export type { UndoFrame, UndoOpKind } from './agent/undo.js'
export { encrypt, decrypt, isEncrypted } from './security/encryption.js'
export { WorkspaceManager } from './workspace/index.js'
export type { WorkspaceData, RepoEntry } from './workspace/index.js'
export { SpecManager, parseSpec, hashSpec } from './spec/index.js'
export type { SpecPlan, SpecTask } from './spec/index.js'
export { chooseArbitrage } from './router/arbitrage.js'
export type { ArbitrageCandidate, ArbitrageOptions, ArbitrageDecision } from './router/arbitrage.js'
export { Tracer, tracer } from './observability/otel.js'
export type { SpanRecord } from './observability/otel.js'
export { AuditLog } from './observability/audit.js'
export type { AuditEntry } from './observability/audit.js'
