/**
 * Build-time generator: turns packages/core/src/skills/bundled/*.md into a
 * compiled-in TypeScript module so the runtime never has to locate the
 * files on disk (which is fragile across ESM/CJS/bundled CLI consumers).
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..', 'packages', 'core', 'src', 'skills')
const SRC = join(ROOT, 'bundled')
const OUT = join(ROOT, 'bundled-content.ts')

async function main() {
  await mkdir(ROOT, { recursive: true })
  const files = (await readdir(SRC)).filter((f) => f.endsWith('.md')).sort()
  const entries: string[] = []
  for (const f of files) {
    const name = basename(f, '.md')
    const content = await readFile(join(SRC, f), 'utf-8')
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(content)},`)
  }

  const out =
`// Auto-generated by scripts/generate-bundled-skills.ts — do not edit by hand.
// Run \`pnpm gen:skills\` to regenerate from packages/core/src/skills/bundled/*.md.

export const BUNDLED_SKILLS: Record<string, string> = {
${entries.join('\n')}
}
`
  await writeFile(OUT, out, 'utf-8')
  console.log(`Wrote ${OUT} (${files.length} skills)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
